In [67]:
import csv
with open("data.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["rajesh","25","Vijayawada"])
    writer.writerow(["mahesh","23","Hyderabad"])

In [68]:
import csv
with open("data.csv","r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['rajesh', '25', 'Vijayawada']
['mahesh', '23', 'Hyderabad']


In [69]:
import numpy as np

In [70]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [71]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [72]:
l=range(1000)
%timeit [i**2 for i in l]

101 μs ± 2.08 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [73]:
l=range(1000)
%timeit [i**2 for i in l]

105 μs ± 1.77 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## creating arrays

In [74]:
a=np.array([1,2,3,4]) #one dimensional array or vectors

In [75]:
print(a.ndim)

1


In [76]:
b=np.array([[1,2,3],[4,5,5]]) #two dimensional array or matrix
print(b)

[[1 2 3]
 [4 5 5]]


In [77]:
print(b.ndim)

2


In [78]:
c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]]) #3 dimensional (in cube)
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
3


In [79]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


# Functions for creating array

In [80]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [82]:
#using linspace
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [83]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [84]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [86]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [87]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [88]:
print(np.diag(a))

[1 2 3 4]


# Basic Data types

In [89]:
a=np.arange(10)
print(a.dtype)

int64


In [90]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [91]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other data types

In [92]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [93]:
a=np.array([True,False])
print(a.dtype)

bool


In [94]:
a=np.array(["aditya degree college"])
print(a.dtype) #unicode string type

<U21


# Indexing and Slicing

In [95]:
a=np.arange(10)
print(a[5])

5


In [96]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [97]:
print(a[0,0])

1


In [98]:
b=np.arange(1,10)
print(b[2:5])

[3 4 5]


# Slicing

In [99]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [100]:
print(a[1:8:3])

[1 4 7]


In [101]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [102]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [103]:
a[1,1]=5
print(a)

[[1 0 0]
 [0 5 0]
 [0 0 3]]


In [104]:
a=np.arange(10)
a[4:]=9
a

array([0, 1, 2, 3, 9, 9, 9, 9, 9, 9])

# copying and viewing

In [105]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [106]:
print(np.shares_memory(a,b))

True


In [107]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [108]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [109]:
print(np.shares_memory(a,b))

False


In [110]:
print(b.base)

None


# random number generator

In [111]:
import numpy as np
a=np.random.randint(0,20,15)
print(a)

[13 17  4  3  1  7  8  3  8 17 16 12  3  4  2]


In [112]:
mask=(a%2==0)
new_a=a[mask]
print(new_a)

[ 4  8  8 16 12  4  2]


In [113]:
a[mask]=-1
print(a)

[13 17 -1  3  1  7 -1  3 -1 17 -1 -1  3 -1 -1]


# Element wise operation
# 1.Basic operator

In [114]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [115]:
print(a**2)

[ 1  4  9 16]


# # All arithmetic operates element wise

In [116]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [117]:
print(a*b)

[2. 4. 6. 8.]


In [118]:
c=np.diag([1,2,3,4])
print(c)
print(c *c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [119]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision operator

In [120]:
a=np.array([1,2,6])
b=np.array([4,5,6])
print(a==b)

[False False  True]


In [121]:
print(a<b)

[ True  True False]


In [122]:
print(a>b)

[False False False]


In [123]:
# array wise comparision
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))

True


# Logical operator

In [124]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [125]:
print(np.logical_and(a,b))

[ True False False False]


In [126]:
print(np.logical_not(a))

[False  True False  True]


# # Trigonometry/Transcendental Functions

In [127]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [128]:
print(np.sin(a))

[0.         0.84147098 0.90929743 0.14112001]


In [129]:
np.log(a)

C:\Users\chait\AppData\Local\Temp\ipykernel_17296\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229])